/**
 * Renderer generico de plantillas de documentos a PDF.
 *
 * Toma una plantilla renderizada (titulo, referencia, body multiline, footer)
 * y genera un PDF A4 con cabecera, cuerpo justificado, firma y disclaimer.
 *
 * Maneja paginacion automatica cuando el body excede la primera pagina.
 * Solo usa caracteres ASCII (Helvetica WinAnsi) para evitar el bug Unicode
 * detectado en modelo650-pdf.
 */

import { PDFDocument, rgb, StandardFonts, PDFPage, PDFFont } from "pdf-lib";

export interface TemplatePdfInput {
  documentTitle: string;
  referenceLine: string | null;
  /** Plain-text body. Paragraphs separated by double newline. */
  body: string;
  footer: string | null;
  /** Header info (sender) for the top of page 1 */
  remitenteName: string;
  remitenteAddress: string;
  remitenteEmail: string;
  remitentePhone: string;
  /** Recipient label printed in the address block */
  recipientLabel: string;
  /** Place + date for signature */
  place?: string;
  /** Generated by line for footer */
  generatedBy: string;
  generatedAt: Date;
}

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN_X = 60;
const MARGIN_TOP = 60;
const MARGIN_BOTTOM = 60;

const NAVY = rgb(0.08, 0.15, 0.35);
const GRAY_DARK = rgb(0.15, 0.15, 0.15);
const GRAY_MID = rgb(0.45, 0.45, 0.45);
const GRAY_LIGHT = rgb(0.85, 0.85, 0.85);
const AMBER_BG = rgb(1, 0.97, 0.88);
const AMBER = rgb(0.55, 0.4, 0);

function formatDate(d: Date): string {
  return d.toLocaleDateString("es-ES", { day: "numeric", month: "long", year: "numeric" });
}

/** Word-wraps a single line into multiple lines that fit within maxWidth. */
function wrapLine(font: PDFFont, line: string, size: number, maxWidth: number): string[] {
  if (font.widthOfTextAtSize(line, size) <= maxWidth) return [line];
  const words = line.split(" ");
  const out: string[] = [];
  let current = "";
  for (const w of words) {
    const candidate = current ? `${current} ${w}` : w;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate;
    } else {
      if (current) out.push(current);
      current = w;
    }
  }
  if (current) out.push(current);
  return out;
}

/**
 * Splits body text into wrapped lines preserving paragraph breaks.
 * Empty strings represent blank lines (paragraph separators).
 */
function bodyToLines(body: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const inputLines = body.replace(/\\n/g, "\n").split("\n");
  const out: string[] = [];
  for (const line of inputLines) {
    if (line.trim() === "") {
      out.push("");
      continue;
    }
    const wrapped = wrapLine(font, line, size, maxWidth);
    out.push(...wrapped);
  }
  return out;
}

export async function generateTemplatePDF(input: TemplatePdfInput): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  pdfDoc.setTitle(input.documentTitle);
  pdfDoc.setAuthor(input.remitenteName);
  pdfDoc.setCreationDate(input.generatedAt);

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const lineHeight = 13;
  const bodySize = 10;
  const titleSize = 12;
  const innerW = PAGE_W - MARGIN_X * 2;

  // Pre-compute wrapped lines for the body so we can paginate
  const bodyLines = bodyToLines(input.body, font, bodySize, innerW);

  // Compute layout: each page has a header zone (sender + recipient + title)
  // on page 1, smaller on subsequent pages.

  let page = pdfDoc.addPage([PAGE_W, PAGE_H]);
  let y = MARGIN_TOP;

  // ── Page 1 header: sender block (left) ───────────────
  const senderStart = y;
  page.drawText(input.remitenteName, { x: MARGIN_X, y: PAGE_H - y - 10, size: 10, font: bold, color: GRAY_DARK });
  y += 14;
  if (input.remitenteAddress) {
    page.drawText(input.remitenteAddress, { x: MARGIN_X, y: PAGE_H - y - 10, size: 9, font, color: GRAY_DARK });
    y += 12;
  }
  if (input.remitenteEmail) {
    page.drawText(input.remitenteEmail, { x: MARGIN_X, y: PAGE_H - y - 10, size: 9, font, color: GRAY_DARK });
    y += 12;
  }
  if (input.remitentePhone) {
    page.drawText(input.remitentePhone, { x: MARGIN_X, y: PAGE_H - y - 10, size: 9, font, color: GRAY_DARK });
    y += 12;
  }

  // Place + date right-aligned
  const placeAndDate = `${input.place ?? "_______________"}, ${formatDate(input.generatedAt)}`;
  const padW = font.widthOfTextAtSize(placeAndDate, 9);
  page.drawText(placeAndDate, { x: PAGE_W - MARGIN_X - padW, y: PAGE_H - senderStart - 10, size: 9, font, color: GRAY_DARK });

  y += 18;

  // ── Recipient label (italic-style with line) ─────────
  page.drawText(input.recipientLabel, { x: MARGIN_X, y: PAGE_H - y - 10, size: 9.5, font: bold, color: GRAY_MID });
  y += 16;

  // ── Document title (centered) ────────────────────────
  const titleW = bold.widthOfTextAtSize(input.documentTitle, titleSize);
  page.drawText(input.documentTitle, {
    x: (PAGE_W - titleW) / 2,
    y: PAGE_H - y - titleSize,
    size: titleSize,
    font: bold,
    color: NAVY,
  });
  y += titleSize + 6;

  // Underline title
  page.drawLine({
    start: { x: MARGIN_X + 80, y: PAGE_H - y },
    end: { x: PAGE_W - MARGIN_X - 80, y: PAGE_H - y },
    thickness: 0.4,
    color: GRAY_LIGHT,
  });
  y += 12;

  // ── Reference line ───────────────────────────────────
  if (input.referenceLine) {
    const refLines = wrapLine(font, input.referenceLine, 9, innerW);
    for (const r of refLines) {
      page.drawText(r, { x: MARGIN_X, y: PAGE_H - y - 9, size: 9, font: bold, color: GRAY_DARK });
      y += 12;
    }
    y += 8;
  }

  // ── Body (paginated) ─────────────────────────────────
  const bottomLimit = PAGE_H - MARGIN_BOTTOM - 80; // leave room for signature/footer

  for (let i = 0; i < bodyLines.length; i++) {
    const line = bodyLines[i];

    if (PAGE_H - y - lineHeight < PAGE_H - bottomLimit) {
      // Page footer (small)
      drawFooterCount(page, font, pdfDoc.getPageCount(), input.generatedBy);
      // New page
      page = pdfDoc.addPage([PAGE_W, PAGE_H]);
      y = MARGIN_TOP;
    }

    if (line === "") {
      y += lineHeight - 4; // smaller gap for paragraph separation
      continue;
    }

    page.drawText(line, { x: MARGIN_X, y: PAGE_H - y - bodySize, size: bodySize, font, color: GRAY_DARK });
    y += lineHeight;
  }

  // ── Signature block ──────────────────────────────────
  y += 30;
  if (PAGE_H - y < MARGIN_BOTTOM + 40) {
    drawFooterCount(page, font, pdfDoc.getPageCount(), input.generatedBy);
    page = pdfDoc.addPage([PAGE_W, PAGE_H]);
    y = MARGIN_TOP;
  }

  const signatureLineY = PAGE_H - y;
  page.drawLine({
    start: { x: MARGIN_X, y: signatureLineY },
    end: { x: MARGIN_X + 200, y: signatureLineY },
    thickness: 0.5,
    color: GRAY_DARK,
  });
  y += 4;
  page.drawText("Firma", { x: MARGIN_X, y: PAGE_H - y - 9, size: 8, font, color: GRAY_MID });
  y += 12;
  page.drawText(`(${input.remitenteName})`, { x: MARGIN_X, y: PAGE_H - y - 9, size: 9, font: bold, color: GRAY_DARK });
  y += 16;

  // ── Footer disclaimer ────────────────────────────────
  if (input.footer) {
    y += 14;
    if (PAGE_H - y < MARGIN_BOTTOM + 40) {
      drawFooterCount(page, font, pdfDoc.getPageCount(), input.generatedBy);
      page = pdfDoc.addPage([PAGE_W, PAGE_H]);
      y = MARGIN_TOP;
    }

    const footerHeight = 30;
    page.drawRectangle({
      x: MARGIN_X - 6,
      y: PAGE_H - y - footerHeight,
      width: innerW + 12,
      height: footerHeight,
      color: AMBER_BG,
    });
    const footerLines = wrapLine(font, input.footer, 8, innerW);
    let fy = y + 10;
    for (const fl of footerLines) {
      page.drawText(fl, { x: MARGIN_X, y: PAGE_H - fy - 8, size: 8, font, color: AMBER });
      fy += 11;
    }
  }

  // Final footer counter
  drawFooterCount(page, font, pdfDoc.getPageCount(), input.generatedBy);

  return pdfDoc.save();
}

function drawFooterCount(page: PDFPage, font: PDFFont, totalPages: number, generatedBy: string) {
  const footerY = 28;
  page.drawText(`Generado por ${generatedBy}`, {
    x: MARGIN_X,
    y: footerY,
    size: 7,
    font,
    color: GRAY_MID,
  });
  const pageLabel = `Pagina ${totalPages}`;
  const pw = font.widthOfTextAtSize(pageLabel, 7);
  page.drawText(pageLabel, {
    x: PAGE_W - MARGIN_X - pw,
    y: footerY,
    size: 7,
    font,
    color: GRAY_MID,
  });
}
